using TUnit.Core;
using DomainBridge.Tests.ConflictScenarios;
using DomainBridge.Tests.ConflictScenarios.ScenarioA;
using DomainBridge.Tests.ConflictScenarios.ScenarioB;

namespace DomainBridge.Tests;

public class UnloadDomainsTests
{
    [After(Assembly)]
    public static void Unload()
    {
        // From InheritanceTests
        DerivedServiceBridge.UnloadDomain();
        ConcreteServiceBridge.UnloadDomain();
        GrandChildServiceBridge.UnloadDomain();
        
        // From original UnloadDomainsTests
        ServiceWithInterfacesBridge.UnloadDomain();
        NestedDataServiceBridge.UnloadDomain();
        StaticFieldTestBridge.UnloadDomain();
        StringServiceBridge.UnloadDomain();
        SecurityTestServiceBridge.UnloadDomain();
        PerformanceTestServiceBridge.UnloadDomain();
        
        // From ComprehensiveFeatureTests
        TestApplicationBridge.UnloadDomain();
        AsyncTestServiceBridge.UnloadDomain();
        CollectionTestServiceBridge.UnloadDomain();
        ErrorTestServiceBridge.UnloadDomain();
        
        // From AutoBridgeGenerationTests
        ServiceWithAutoGeneratedReturnsBridge.UnloadDomain();
        
        // From ConflictResolutionTests
        InvoiceBridge.UnloadDomain();
        OrderBridge.UnloadDomain();
        
        // From EdgeCaseAndErrorTests
        EdgeCaseTestServiceBridge.UnloadDomain();
        
        // From FactoryMethodTests
        ServiceWithConstructorArgsBridge.UnloadDomain();
        ComplexServiceBridge.UnloadDomain();
        
        // From InterfaceImplementationTests
        ExampleServiceBridge.UnloadDomain();
        
        // From KeywordParameterTests
        EventServiceBridge.UnloadDomain();
    }
}